/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bank_system;

import database_operations.account_operations;
import database_operations.customer_search;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author IBOYSL
 */
public class Cashier extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    public Cashier() {
        initComponents();
        Calendar();
   
        customer_list_panel.setVisible(false);
        balance_panel.setVisible(false);

    }
    
        public void Calendar(){
        Calendar cal = new GregorianCalendar();
        int month=cal.get(Calendar.MONTH);
        int year=cal.get(Calendar.YEAR);
        int day=cal.get(Calendar.DAY_OF_MONTH);
        jTextField2.setText(+day+"-"+(month+1)+"-"+year);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        acc_details = new javax.swing.JPanel();
        customer_list_but = new javax.swing.JButton();
        customer_bal = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        customer_list_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_table = new javax.swing.JTable();
        search_index = new javax.swing.JTextField();
        search_but = new javax.swing.JButton();
        clear_but = new javax.swing.JButton();
        search_all = new javax.swing.JButton();
        search_filter = new javax.swing.JComboBox<>();
        balance_panel = new javax.swing.JPanel();
        search_bal = new javax.swing.JButton();
        acc_no_view = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        name_view = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        acc_view = new javax.swing.JTextField();
        a_bal = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nic_view = new javax.swing.JTextField();
        transaction_panel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        t_name = new javax.swing.JTextField();
        t_search = new javax.swing.JButton();
        t_accNo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        t_bal = new javax.swing.JTextField();
        dipo_amount = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        after_dipo = new javax.swing.JTextField();
        remain_bal = new javax.swing.JButton();
        dip_but = new javax.swing.JButton();
        with_but = new javax.swing.JButton();
        after_with = new javax.swing.JTextField();
        remain_bal_with = new javax.swing.JButton();
        with_amount = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255)));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-export-30.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 3, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ug-sbu-logo1 micro.png"))); // NOI18N
        jLabel2.setText("BT Bank SriLanka");

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102)));

        customer_list_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customer_list_but.setText("Customer List");
        customer_list_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_list_butActionPerformed(evt);
            }
        });

        customer_bal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customer_bal.setText("View Balance");
        customer_bal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_balActionPerformed(evt);
            }
        });

        customer_list_panel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        customer_list_panel.setPreferredSize(new java.awt.Dimension(753, 523));

        list_table.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        list_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(list_table);

        search_index.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_indexActionPerformed(evt);
            }
        });

        search_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-search-26.png"))); // NOI18N
        search_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_butActionPerformed(evt);
            }
        });

        clear_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-waste-24.png"))); // NOI18N
        clear_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_butActionPerformed(evt);
            }
        });

        search_all.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-search-property-48.png"))); // NOI18N
        search_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_allActionPerformed(evt);
            }
        });

        search_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "By name", "By Acc No." }));

        javax.swing.GroupLayout customer_list_panelLayout = new javax.swing.GroupLayout(customer_list_panel);
        customer_list_panel.setLayout(customer_list_panelLayout);
        customer_list_panelLayout.setHorizontalGroup(
            customer_list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customer_list_panelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(customer_list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_all, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customer_list_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search_index, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(search_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(search_but)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clear_but)
                .addGap(40, 40, 40))
        );
        customer_list_panelLayout.setVerticalGroup(
            customer_list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customer_list_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search_all, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(customer_list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customer_list_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(search_but))
                    .addGroup(customer_list_panelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(customer_list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customer_list_panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clear_but, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(customer_list_panelLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(customer_list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(search_filter)
                                    .addComponent(search_index))))))
                .addGap(52, 52, 52))
        );

        balance_panel.setPreferredSize(new java.awt.Dimension(753, 523));

        search_bal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-search-26.png"))); // NOI18N
        search_bal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_balActionPerformed(evt);
            }
        });

        acc_no_view.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Name");

        name_view.setEditable(false);
        name_view.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Account No.");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Account type");

        acc_view.setEditable(false);
        acc_view.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        a_bal.setEditable(false);
        a_bal.setFont(new java.awt.Font("Baskerville Old Face", 0, 36)); // NOI18N
        a_bal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_balActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Available Balance");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("NIC");

        nic_view.setEditable(false);

        javax.swing.GroupLayout balance_panelLayout = new javax.swing.GroupLayout(balance_panel);
        balance_panel.setLayout(balance_panelLayout);
        balance_panelLayout.setHorizontalGroup(
            balance_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, balance_panelLayout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addGroup(balance_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, balance_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(balance_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(balance_panelLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(balance_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel1))
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, balance_panelLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(37, 37, 37)))
                        .addGroup(balance_panelLayout.createSequentialGroup()
                            .addComponent(jLabel26)
                            .addGap(37, 37, 37)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, balance_panelLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(28, 28, 28)))
                .addGroup(balance_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(acc_no_view)
                    .addComponent(name_view)
                    .addComponent(acc_view, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(nic_view)
                    .addComponent(a_bal))
                .addGap(88, 88, 88)
                .addComponent(search_bal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        balance_panelLayout.setVerticalGroup(
            balance_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balance_panelLayout.createSequentialGroup()
                .addGroup(balance_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(balance_panelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(balance_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acc_no_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(28, 28, 28)
                        .addGroup(balance_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)))
                    .addGroup(balance_panelLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(search_bal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(balance_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nic_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(balance_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acc_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(44, 44, 44)
                .addGroup(balance_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a_bal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(118, 118, 118))
        );

        jLayeredPane1.setLayer(customer_list_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(balance_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(customer_list_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(balance_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(customer_list_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(balance_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout acc_detailsLayout = new javax.swing.GroupLayout(acc_details);
        acc_details.setLayout(acc_detailsLayout);
        acc_detailsLayout.setHorizontalGroup(
            acc_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acc_detailsLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(customer_list_but)
                .addGap(31, 31, 31)
                .addComponent(customer_bal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLayeredPane1)
        );
        acc_detailsLayout.setVerticalGroup(
            acc_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acc_detailsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(acc_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer_list_but)
                    .addComponent(customer_bal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1))
        );

        jTabbedPane1.addTab("Account Details", acc_details);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Name");

        t_name.setEditable(false);
        t_name.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        t_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-search-26.png"))); // NOI18N
        t_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_searchActionPerformed(evt);
            }
        });

        t_accNo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        t_accNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_accNoActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Account No.");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Available Balance");

        t_bal.setEditable(false);
        t_bal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        dipo_amount.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Diposit amount");

        after_dipo.setEditable(false);
        after_dipo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        remain_bal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-check-mark-32.png"))); // NOI18N
        remain_bal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remain_balActionPerformed(evt);
            }
        });

        dip_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-deposit-48.png"))); // NOI18N
        dip_but.setText("Diposit");
        dip_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dip_butActionPerformed(evt);
            }
        });

        with_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-withdrawal-48.png"))); // NOI18N
        with_but.setText("Withdraw");
        with_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                with_butActionPerformed(evt);
            }
        });

        after_with.setEditable(false);
        after_with.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        remain_bal_with.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-check-mark-32.png"))); // NOI18N
        remain_bal_with.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remain_bal_withActionPerformed(evt);
            }
        });

        with_amount.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Withdraw amount");

        javax.swing.GroupLayout transaction_panelLayout = new javax.swing.GroupLayout(transaction_panel);
        transaction_panel.setLayout(transaction_panelLayout);
        transaction_panelLayout.setHorizontalGroup(
            transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaction_panelLayout.createSequentialGroup()
                .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaction_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(56, 56, 56)
                        .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t_name, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(t_bal))
                            .addComponent(t_accNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaction_panelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(transaction_panelLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(with_amount))
                            .addGroup(transaction_panelLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(dipo_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55)
                        .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(after_dipo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(after_with, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transaction_panelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(t_search, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(transaction_panelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(with_but)
                            .addComponent(dip_but, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(remain_bal_with, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(remain_bal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(187, 187, 187))
        );
        transaction_panelLayout.setVerticalGroup(
            transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaction_panelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(t_accNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(t_search))
                .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transaction_panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(t_bal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(transaction_panelLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(remain_bal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(dipo_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(after_dipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(dip_but, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(after_with)
                            .addComponent(with_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(remain_bal_with, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(with_but, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        jTabbedPane1.addTab("Transection", transaction_panel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(803, 797));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void search_indexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_indexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_indexActionPerformed

    private void search_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_allActionPerformed
        // TODO add your handling code here:
        customer_search obj = new customer_search();
        obj.customer_list(list_table);
        
    }//GEN-LAST:event_search_allActionPerformed

    private void a_balActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_balActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_balActionPerformed

    private void customer_list_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_list_butActionPerformed
        // TODO add your handling code here:

        customer_list_panel.setVisible(true);
        balance_panel.setVisible(false);
    }//GEN-LAST:event_customer_list_butActionPerformed

    private void customer_balActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_balActionPerformed
        // TODO add your handling code here:

        customer_list_panel.setVisible(false);
        balance_panel.setVisible(true);
    }//GEN-LAST:event_customer_balActionPerformed

    private void t_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_searchActionPerformed
        // TODO add your handling code here:
        account_operations obj = new account_operations();
         obj.view_balance(Integer.parseInt(t_accNo.getText()), t_name, acc_view, nic_view, t_bal);
        
    }//GEN-LAST:event_t_searchActionPerformed

    private void remain_balActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remain_balActionPerformed
        // TODO add your handling code here:
        Double a1 = Double.parseDouble(t_bal.getText());
            Double a2 = Double.parseDouble(dipo_amount.getText());
            Double sum= a1+a2;
            
            after_dipo.setText(sum.toString());
    }//GEN-LAST:event_remain_balActionPerformed

    private void dip_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dip_butActionPerformed
        // TODO add your handling code here:
        
            Double a1 = Double.parseDouble(t_bal.getText());
            Double a2 = Double.parseDouble(dipo_amount.getText());
          
            account_operations obj = new account_operations();
            obj.acount_deposit(Integer.parseInt(t_accNo.getText()),a1,a2);
            
            
            t_name.setText("");
            t_accNo.setText("");
            t_bal.setText("");
            dipo_amount.setText("");
            after_dipo.setText("");

        
    }//GEN-LAST:event_dip_butActionPerformed

    private void with_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_with_butActionPerformed
        // TODO add your handling code here:
        Double a1 = Double.parseDouble(t_bal.getText());
            Double a2 = Double.parseDouble(with_amount.getText());
          
            account_operations obj = new account_operations();
            obj.account_withdraw(Integer.parseInt(t_accNo.getText()), a1, a2);
            
            
            t_name.setText("");
            t_accNo.setText("");
            t_bal.setText("");
            with_amount.setText("");
            after_with.setText("");
    }//GEN-LAST:event_with_butActionPerformed

    private void remain_bal_withActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remain_bal_withActionPerformed
        // TODO add your handling code here:
        
        Double a1 = Double.parseDouble(t_bal.getText());
            Double a2 = Double.parseDouble(with_amount.getText());
            Double sum= a1-a2;
            
            after_with.setText(sum.toString());
        
    }//GEN-LAST:event_remain_bal_withActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void search_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_butActionPerformed
        // TODO add your handling code here:
        String search = search_index.getText();
        
        
        String filter =search_filter.getSelectedItem().toString();
        
        try{
            if(filter=="By Acc No."){
                    
                  customer_search obj = new  customer_search();
                  obj.AccNo_filter(list_table, search);
                    
            }
            else if(filter=="By name"){
                    customer_search obj = new  customer_search();
                    obj.name_filter(list_table, search);
            }
        }catch(Exception e){
        System.out.println(e);

        }
        
    }//GEN-LAST:event_search_butActionPerformed

    private void clear_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_butActionPerformed
        // TODO add your handling code here:
        
        search_index.setText("");
    }//GEN-LAST:event_clear_butActionPerformed

    private void search_balActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_balActionPerformed
        // TODO add your handling code here:
        account_operations obj = new account_operations();
         obj.view_balance(Integer.parseInt(acc_no_view.getText()), name_view, acc_view, nic_view, a_bal);
    }//GEN-LAST:event_search_balActionPerformed

    private void t_accNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_accNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_accNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a_bal;
    private javax.swing.JPanel acc_details;
    private javax.swing.JTextField acc_no_view;
    private javax.swing.JTextField acc_view;
    private javax.swing.JTextField after_dipo;
    private javax.swing.JTextField after_with;
    private javax.swing.JPanel balance_panel;
    private javax.swing.JButton clear_but;
    private javax.swing.JButton customer_bal;
    private javax.swing.JButton customer_list_but;
    private javax.swing.JPanel customer_list_panel;
    private javax.swing.JButton dip_but;
    private javax.swing.JTextField dipo_amount;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable list_table;
    private javax.swing.JTextField name_view;
    private javax.swing.JTextField nic_view;
    private javax.swing.JButton remain_bal;
    private javax.swing.JButton remain_bal_with;
    private javax.swing.JButton search_all;
    private javax.swing.JButton search_bal;
    private javax.swing.JButton search_but;
    private javax.swing.JComboBox<String> search_filter;
    private javax.swing.JTextField search_index;
    private javax.swing.JTextField t_accNo;
    private javax.swing.JTextField t_bal;
    private javax.swing.JTextField t_name;
    private javax.swing.JButton t_search;
    private javax.swing.JPanel transaction_panel;
    private javax.swing.JTextField with_amount;
    private javax.swing.JButton with_but;
    // End of variables declaration//GEN-END:variables
}
