/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bank_system;

import database_operations.account_operations;
import database_operations.customer_search;
import database_operations.manager_search;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author IBOYSL
 */
public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    public Manager() {
        initComponents();
        Calendar();
        add_account_panel.setVisible(false);
        customer_list_panel.setVisible(false);
        view_bal_panel.setVisible(false);
        officer_list_pane.setVisible(false);
        add_officer_panel.setVisible(false);
    }
    
        public void Calendar(){
        Calendar cal = new GregorianCalendar();
        int month=cal.get(Calendar.MONTH);
        int year=cal.get(Calendar.YEAR);
        int day=cal.get(Calendar.DAY_OF_MONTH);
        date.setText(+day+"-"+(month+1)+"-"+year);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        logout_but = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        account_panel = new javax.swing.JPanel();
        add_account_butt = new javax.swing.JButton();
        customer_list_but = new javax.swing.JButton();
        view_bal_but = new javax.swing.JButton();
        sub_panel = new javax.swing.JLayeredPane();
        add_account_panel = new javax.swing.JPanel();
        male_radio = new javax.swing.JRadioButton();
        female_radio = new javax.swing.JRadioButton();
        acc_create_but = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        acc_creat_clear_but = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        acc_type_combo = new javax.swing.JComboBox<>();
        cus_name_txt = new javax.swing.JTextField();
        address_txt = new javax.swing.JTextField();
        nic_txt = new javax.swing.JTextField();
        mobile_txt = new javax.swing.JTextField();
        amount_txt = new javax.swing.JTextField();
        year = new javax.swing.JComboBox<>();
        day = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        dob_txt = new javax.swing.JTextField();
        customer_list_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customer_table = new javax.swing.JTable();
        search_txt = new javax.swing.JTextField();
        customer_search_but = new javax.swing.JButton();
        clear_search_txt = new javax.swing.JButton();
        search_all = new javax.swing.JButton();
        search_filter = new javax.swing.JComboBox<>();
        view_bal_panel = new javax.swing.JPanel();
        bal_search = new javax.swing.JButton();
        acc_txt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        acc_field = new javax.swing.JTextField();
        balance_field = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nic_field = new javax.swing.JTextField();
        name_field = new javax.swing.JTextField();
        transaction_panel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        t_name = new javax.swing.JTextField();
        transaction_search = new javax.swing.JButton();
        t_accNo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        t_bal = new javax.swing.JTextField();
        diposit_amount = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        bal_update = new javax.swing.JTextField();
        check_diposit = new javax.swing.JButton();
        diposit_but = new javax.swing.JButton();
        withdraw_but = new javax.swing.JButton();
        after_withdraw = new javax.swing.JTextField();
        check_withdraw = new javax.swing.JButton();
        withdraw_amount = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        officer_panel = new javax.swing.JPanel();
        add_officer_but = new javax.swing.JButton();
        officer_list_panel = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        officer_list_pane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        officer_list = new javax.swing.JTable();
        officer_search = new javax.swing.JButton();
        add_officer_panel = new javax.swing.JPanel();
        officer_add = new javax.swing.JButton();
        off_cleat = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        male_off = new javax.swing.JRadioButton();
        female_off = new javax.swing.JRadioButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        role_off = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        name_off = new javax.swing.JTextField();
        password_off = new javax.swing.JTextField();
        address_off = new javax.swing.JTextField();
        nic_off = new javax.swing.JTextField();
        mobile_off = new javax.swing.JTextField();
        dob_off = new javax.swing.JTextField();
        day_off = new javax.swing.JComboBox<>();
        month_off = new javax.swing.JComboBox<>();
        year_off = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255)));

        logout_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-export-30.png"))); // NOI18N
        logout_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_butActionPerformed(evt);
            }
        });

        logo.setFont(new java.awt.Font("OCR A Extended", 3, 12)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ug-sbu-logo1 micro.png"))); // NOI18N
        logo.setText("BT Bank SriLanka");

        date.setEditable(false);
        date.setBackground(new java.awt.Color(204, 204, 204));
        date.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        date.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102)));

        add_account_butt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add_account_butt.setText("Add Account");
        add_account_butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_account_buttActionPerformed(evt);
            }
        });

        customer_list_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customer_list_but.setText("Customer List");
        customer_list_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_list_butActionPerformed(evt);
            }
        });

        view_bal_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        view_bal_but.setText("View Balance");
        view_bal_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_bal_butActionPerformed(evt);
            }
        });

        add_account_panel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        buttonGroup1.add(male_radio);
        male_radio.setText("Male");

        buttonGroup1.add(female_radio);
        female_radio.setText("Female");

        acc_create_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-add-user-male-16.png"))); // NOI18N
        acc_create_but.setText("Create");
        acc_create_but.setAlignmentX(0.5F);
        acc_create_but.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        acc_create_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acc_create_butActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setText("Name");

        acc_creat_clear_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-eraser-16.png"))); // NOI18N
        acc_creat_clear_but.setText("Clear");
        acc_creat_clear_but.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        acc_creat_clear_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acc_creat_clear_butActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setText("Date of Birth");

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setText("Gender");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setText("Amount");

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel44.setText("Address");

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setText("NIC");

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setText("Mobile");

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setText("Account type");

        acc_type_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Savings account", "Current account", "Join account", "Fix account" }));

        cus_name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cus_name_txtActionPerformed(evt);
            }
        });

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });

        dob_txt.setEditable(false);

        javax.swing.GroupLayout add_account_panelLayout = new javax.swing.GroupLayout(add_account_panel);
        add_account_panel.setLayout(add_account_panelLayout);
        add_account_panelLayout.setHorizontalGroup(
            add_account_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_account_panelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(add_account_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel40)
                    .addComponent(jLabel47)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42)
                    .addComponent(jLabel44)
                    .addComponent(jLabel45)
                    .addComponent(jLabel46)
                    .addComponent(jLabel43))
                .addGap(18, 18, 18)
                .addGroup(add_account_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_account_panelLayout.createSequentialGroup()
                        .addGroup(add_account_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(add_account_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(add_account_panelLayout.createSequentialGroup()
                                    .addComponent(male_radio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(female_radio, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(acc_type_combo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cus_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(264, 264, 264)
                        .addGroup(add_account_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acc_create_but, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acc_creat_clear_but, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(add_account_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(amount_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(mobile_txt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nic_txt, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(add_account_panelLayout.createSequentialGroup()
                        .addComponent(dob_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        add_account_panelLayout.setVerticalGroup(
            add_account_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_account_panelLayout.createSequentialGroup()
                .addGroup(add_account_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_account_panelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(acc_create_but, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(acc_creat_clear_but, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(add_account_panelLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(add_account_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(cus_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(add_account_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acc_type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel47))
                        .addGap(21, 21, 21)
                        .addGroup(add_account_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dob_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(add_account_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(add_account_panelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(add_account_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(male_radio)
                                    .addComponent(female_radio)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_account_panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addGroup(add_account_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44))
                        .addGap(18, 18, 18)
                        .addGroup(add_account_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(nic_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(add_account_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mobile_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel46))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(add_account_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(amount_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        customer_list_panel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        customer_list_panel.setPreferredSize(new java.awt.Dimension(753, 523));

        customer_table.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        customer_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(customer_table);

        search_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_txtActionPerformed(evt);
            }
        });

        customer_search_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-search-26.png"))); // NOI18N
        customer_search_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_search_butActionPerformed(evt);
            }
        });

        clear_search_txt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-waste-24.png"))); // NOI18N
        clear_search_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_search_txtActionPerformed(evt);
            }
        });

        search_all.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-search-property-48.png"))); // NOI18N
        search_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_allActionPerformed(evt);
            }
        });

        search_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "By Acc No.", "By Name" }));

        javax.swing.GroupLayout customer_list_panelLayout = new javax.swing.GroupLayout(customer_list_panel);
        customer_list_panel.setLayout(customer_list_panelLayout);
        customer_list_panelLayout.setHorizontalGroup(
            customer_list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customer_list_panelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(customer_list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_all, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customer_list_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(search_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(customer_search_but)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clear_search_txt)
                .addGap(40, 40, 40))
        );
        customer_list_panelLayout.setVerticalGroup(
            customer_list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customer_list_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search_all, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(customer_list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customer_list_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(customer_search_but))
                    .addGroup(customer_list_panelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(customer_list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customer_list_panelLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(customer_list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(search_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(customer_list_panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clear_search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        view_bal_panel.setPreferredSize(new java.awt.Dimension(753, 523));

        bal_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-search-26.png"))); // NOI18N
        bal_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bal_searchActionPerformed(evt);
            }
        });

        acc_txt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Name");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Account No.");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Account type");

        acc_field.setEditable(false);
        acc_field.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        balance_field.setEditable(false);
        balance_field.setFont(new java.awt.Font("Baskerville Old Face", 0, 36)); // NOI18N
        balance_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balance_fieldActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Available Balance");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("NIC");

        nic_field.setEditable(false);

        name_field.setEditable(false);

        javax.swing.GroupLayout view_bal_panelLayout = new javax.swing.GroupLayout(view_bal_panel);
        view_bal_panel.setLayout(view_bal_panelLayout);
        view_bal_panelLayout.setHorizontalGroup(
            view_bal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_bal_panelLayout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(view_bal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(36, 36, 36)
                .addGroup(view_bal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(balance_field, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(acc_txt)
                    .addComponent(acc_field, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(nic_field)
                    .addComponent(name_field))
                .addGap(68, 68, 68)
                .addComponent(bal_search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        view_bal_panelLayout.setVerticalGroup(
            view_bal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_bal_panelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(view_bal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(view_bal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(acc_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24))
                    .addComponent(bal_search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(view_bal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(view_bal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nic_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(view_bal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acc_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(23, 23, 23)
                .addGroup(view_bal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(balance_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(197, 197, 197))
        );

        sub_panel.setLayer(add_account_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sub_panel.setLayer(customer_list_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sub_panel.setLayer(view_bal_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout sub_panelLayout = new javax.swing.GroupLayout(sub_panel);
        sub_panel.setLayout(sub_panelLayout);
        sub_panelLayout.setHorizontalGroup(
            sub_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add_account_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sub_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(customer_list_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE))
            .addGroup(sub_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(view_bal_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE))
        );
        sub_panelLayout.setVerticalGroup(
            sub_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add_account_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sub_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(customer_list_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
            .addGroup(sub_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(view_bal_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout account_panelLayout = new javax.swing.GroupLayout(account_panel);
        account_panel.setLayout(account_panelLayout);
        account_panelLayout.setHorizontalGroup(
            account_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(account_panelLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(add_account_butt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(customer_list_but)
                .addGap(28, 28, 28)
                .addComponent(view_bal_but, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
            .addComponent(sub_panel)
        );
        account_panelLayout.setVerticalGroup(
            account_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(account_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(account_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_account_butt)
                    .addComponent(customer_list_but)
                    .addComponent(view_bal_but))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sub_panel))
        );

        jTabbedPane1.addTab("Account Details", account_panel);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Name");

        t_name.setEditable(false);
        t_name.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        transaction_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-search-26.png"))); // NOI18N
        transaction_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaction_searchActionPerformed(evt);
            }
        });

        t_accNo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Account No.");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Available Balance");

        t_bal.setEditable(false);
        t_bal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        diposit_amount.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Diposit amount");

        bal_update.setEditable(false);
        bal_update.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        check_diposit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-check-mark-32.png"))); // NOI18N
        check_diposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_dipositActionPerformed(evt);
            }
        });

        diposit_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-deposit-48.png"))); // NOI18N
        diposit_but.setText("Diposit");
        diposit_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diposit_butActionPerformed(evt);
            }
        });

        withdraw_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-withdrawal-48.png"))); // NOI18N
        withdraw_but.setText("Withdraw");
        withdraw_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdraw_butActionPerformed(evt);
            }
        });

        after_withdraw.setEditable(false);
        after_withdraw.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        check_withdraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-check-mark-32.png"))); // NOI18N
        check_withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_withdrawActionPerformed(evt);
            }
        });

        withdraw_amount.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Withdraw amount");

        javax.swing.GroupLayout transaction_panelLayout = new javax.swing.GroupLayout(transaction_panel);
        transaction_panel.setLayout(transaction_panelLayout);
        transaction_panelLayout.setHorizontalGroup(
            transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaction_panelLayout.createSequentialGroup()
                .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaction_panelLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(transaction_panelLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(56, 56, 56))
                            .addGroup(transaction_panelLayout.createSequentialGroup()
                                .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addGap(48, 48, 48)))
                        .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_name)
                            .addComponent(t_bal)
                            .addComponent(t_accNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaction_panelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(transaction_panelLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(withdraw_amount))
                            .addGroup(transaction_panelLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(diposit_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55)
                        .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bal_update, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(after_withdraw, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transaction_panelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(transaction_search, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(transaction_panelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(withdraw_but)
                            .addComponent(diposit_but, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(check_withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(check_diposit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48))
        );
        transaction_panelLayout.setVerticalGroup(
            transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaction_panelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t_accNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addComponent(transaction_search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transaction_panelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(t_bal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(transaction_panelLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(check_diposit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, Short.MAX_VALUE)
                            .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(diposit_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bal_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(diposit_but, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(transaction_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(after_withdraw)
                            .addComponent(withdraw_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(check_withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(withdraw_but, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        jTabbedPane1.addTab("Transection", transaction_panel);

        add_officer_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add_officer_but.setText("Add officer");
        add_officer_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_officer_butActionPerformed(evt);
            }
        });

        officer_list_panel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        officer_list_panel.setText("Officer List");
        officer_list_panel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officer_list_panelActionPerformed(evt);
            }
        });

        jLayeredPane2.setPreferredSize(new java.awt.Dimension(754, 523));

        officer_list_pane.setPreferredSize(new java.awt.Dimension(754, 523));

        officer_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(officer_list);

        officer_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-search-property-48.png"))); // NOI18N
        officer_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officer_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout officer_list_paneLayout = new javax.swing.GroupLayout(officer_list_pane);
        officer_list_pane.setLayout(officer_list_paneLayout);
        officer_list_paneLayout.setHorizontalGroup(
            officer_list_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(officer_list_paneLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(officer_list_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(officer_search, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 51, Short.MAX_VALUE))
        );
        officer_list_paneLayout.setVerticalGroup(
            officer_list_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, officer_list_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(officer_search, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        add_officer_panel.setPreferredSize(new java.awt.Dimension(754, 523));

        officer_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-add-user-male-16.png"))); // NOI18N
        officer_add.setText("Add");
        officer_add.setAlignmentX(0.5F);
        officer_add.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        officer_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officer_addActionPerformed(evt);
            }
        });

        off_cleat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-eraser-16.png"))); // NOI18N
        off_cleat.setText("Clear");
        off_cleat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        off_cleat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                off_cleatActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText("Name");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("Password");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Date of Birth");

        buttonGroup2.add(male_off);
        male_off.setText("male");

        buttonGroup2.add(female_off);
        female_off.setText("Female");
        female_off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_offActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("Gender");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Address");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Nic");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setText("Mobile");

        role_off.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Cashier" }));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setText("Possition");

        dob_off.setEditable(false);

        day_off.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        month_off.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        year_off.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));

        javax.swing.GroupLayout add_officer_panelLayout = new javax.swing.GroupLayout(add_officer_panel);
        add_officer_panel.setLayout(add_officer_panelLayout);
        add_officer_panelLayout.setHorizontalGroup(
            add_officer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_officer_panelLayout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addGroup(add_officer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel37)
                    .addComponent(jLabel36)
                    .addComponent(jLabel27)
                    .addComponent(jLabel33)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel34)
                    .addComponent(jLabel38))
                .addGap(18, 18, 18)
                .addGroup(add_officer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_officer_panelLayout.createSequentialGroup()
                        .addComponent(officer_add, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(off_cleat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(add_officer_panelLayout.createSequentialGroup()
                        .addGroup(add_officer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password_off)
                            .addGroup(add_officer_panelLayout.createSequentialGroup()
                                .addGroup(add_officer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name_off, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(add_officer_panelLayout.createSequentialGroup()
                                        .addComponent(male_off)
                                        .addGap(18, 18, 18)
                                        .addComponent(female_off))
                                    .addComponent(address_off, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nic_off, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mobile_off, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(287, 287, 287))
                    .addGroup(add_officer_panelLayout.createSequentialGroup()
                        .addGroup(add_officer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(role_off, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(add_officer_panelLayout.createSequentialGroup()
                                .addComponent(dob_off, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day_off, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(month_off, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(year_off, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        add_officer_panelLayout.setVerticalGroup(
            add_officer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_officer_panelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(add_officer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(name_off, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(add_officer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(password_off, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_officer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(dob_off, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day_off, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month_off, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year_off, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_officer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(male_off)
                    .addComponent(female_off))
                .addGap(18, 18, 18)
                .addGroup(add_officer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(address_off, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_officer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(nic_off, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_officer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(mobile_off, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(add_officer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(role_off, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(add_officer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(officer_add, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(off_cleat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jLayeredPane2.setLayer(officer_list_pane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(add_officer_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add_officer_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addComponent(officer_list_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add_officer_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(officer_list_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout officer_panelLayout = new javax.swing.GroupLayout(officer_panel);
        officer_panel.setLayout(officer_panelLayout);
        officer_panelLayout.setHorizontalGroup(
            officer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, officer_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_officer_but)
                .addGap(53, 53, 53)
                .addComponent(officer_list_panel)
                .addGap(108, 108, 108))
            .addGroup(officer_panelLayout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        officer_panelLayout.setVerticalGroup(
            officer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(officer_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(officer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_officer_but)
                    .addComponent(officer_list_panel))
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Officer Details", officer_panel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout_but, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logo))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logout_but, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logo)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(803, 797));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void add_account_buttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_account_buttActionPerformed
        // TODO add your handling code here:
        add_account_panel.setVisible(true);
        customer_list_panel.setVisible(false);
        view_bal_panel.setVisible(false);
    }//GEN-LAST:event_add_account_buttActionPerformed

    private void acc_create_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acc_create_butActionPerformed
       
       String day_txt = day.getSelectedItem().toString();
       String month_txt =month.getSelectedItem().toString();
       String year_txt =year.getSelectedItem().toString();
       String dob_fixed =day_txt+"/"+month_txt+"/"+year_txt;
       String gender = null ;
       
       if(male_radio.isSelected()){
           gender ="male";
       }else if(female_radio.isSelected()){
           gender ="female";
       }
       dob_txt.setText(dob_fixed);
       
        account_operations obj = new account_operations();
        int x=obj.new_customer(cus_name_txt.getText().toString(), acc_type_combo.getSelectedItem().toString(), dob_fixed, gender, address_txt.getText().toString(), nic_txt.getText().toString(), mobile_txt.getText().toString(), Double.parseDouble(amount_txt.getText()));
        
        if(x==1){
            JOptionPane.showMessageDialog(null, "'"+cus_name_txt.getText().toString()+"' added to system succesfully");
        }else{
            JOptionPane.showMessageDialog(null, "something went wrong!!!");
        }
    }//GEN-LAST:event_acc_create_butActionPerformed

    private void acc_creat_clear_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acc_creat_clear_butActionPerformed
        // TODO add your handling code here:
        
        cus_name_txt.setText("");
        address_txt.setText("");
        nic_txt.setText("");
        mobile_txt.setText("");
        amount_txt.setText("");
    }//GEN-LAST:event_acc_creat_clear_butActionPerformed

    private void cus_name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cus_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cus_name_txtActionPerformed

    private void search_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_txtActionPerformed

    private void search_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_allActionPerformed
        // TODO add your handling code here:
        
        customer_search obj = new customer_search();
        obj.customer_list(customer_table);
        
    }//GEN-LAST:event_search_allActionPerformed

    private void balance_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balance_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balance_fieldActionPerformed

    private void customer_list_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_list_butActionPerformed
        // TODO add your handling code here:
        add_account_panel.setVisible(false);
        customer_list_panel.setVisible(true);
        view_bal_panel.setVisible(false);
    }//GEN-LAST:event_customer_list_butActionPerformed

    private void view_bal_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_bal_butActionPerformed
        // TODO add your handling code here:
        add_account_panel.setVisible(false);
        customer_list_panel.setVisible(false);
        view_bal_panel.setVisible(true);
    }//GEN-LAST:event_view_bal_butActionPerformed

    private void transaction_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaction_searchActionPerformed
        // TODO add your handling code here:
        
         account_operations obj = new account_operations();
         obj.view_balance(Integer.parseInt(t_accNo.getText()), t_name, acc_field, nic_field, t_bal);
    }//GEN-LAST:event_transaction_searchActionPerformed

    private void check_dipositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_dipositActionPerformed
        // TODO add your handling code here:
        
            Double a1 = Double.parseDouble(t_bal.getText());
            Double a2 = Double.parseDouble(diposit_amount.getText());
            Double sum= a1+a2;
            
            bal_update.setText(sum.toString());
        
    }//GEN-LAST:event_check_dipositActionPerformed

    private void diposit_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diposit_butActionPerformed
        // TODO add your handling code here:
       
            Double a1 = Double.parseDouble(t_bal.getText());
            Double a2 = Double.parseDouble(diposit_amount.getText());
          
            account_operations obj = new account_operations();
            obj.acount_deposit(Integer.parseInt(t_accNo.getText()),a1,a2);
            
            
            t_name.setText("");
            t_accNo.setText("");
            t_bal.setText("");
            diposit_amount.setText("");
            bal_update.setText("");

        
            
        
    }//GEN-LAST:event_diposit_butActionPerformed

    private void withdraw_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdraw_butActionPerformed
        // TODO add your handling code here:
       
            
            Double a1 = Double.parseDouble(t_bal.getText());
            Double a2 = Double.parseDouble(withdraw_amount.getText());
          
            account_operations obj = new account_operations();
            obj.account_withdraw(Integer.parseInt(t_accNo.getText()), a1, a2);
            
            
            t_name.setText("");
            t_accNo.setText("");
            t_bal.setText("");
            withdraw_amount.setText("");
            after_withdraw.setText("");

       
    }//GEN-LAST:event_withdraw_butActionPerformed

    private void check_withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_withdrawActionPerformed
        // TODO add your handling code here:
            Double a1 = Double.parseDouble(t_bal.getText());
            Double a2 = Double.parseDouble(withdraw_amount.getText());
            Double sum= a1-a2;
            
            after_withdraw.setText(sum.toString());
        
      
    }//GEN-LAST:event_check_withdrawActionPerformed

    private void add_officer_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_officer_butActionPerformed
        // TODO add your handling code here:
        add_officer_panel.setVisible(true);
        officer_list_pane.setVisible(false);
    }//GEN-LAST:event_add_officer_butActionPerformed

    private void off_cleatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_off_cleatActionPerformed
        // TODO add your handling code here:
        name_off.setText("");
        password_off.setText("");
       
        address_off.setText("");
        nic_off.setText("");
        mobile_off.setText("");
       
    }//GEN-LAST:event_off_cleatActionPerformed

    private void female_offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_offActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_female_offActionPerformed

    private void officer_list_panelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officer_list_panelActionPerformed
        // TODO add your handling code here:
        add_officer_panel.setVisible(false);
        officer_list_pane.setVisible(true);
    }//GEN-LAST:event_officer_list_panelActionPerformed

    private void logout_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_butActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logout_butActionPerformed

    private void customer_search_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_search_butActionPerformed
        // TODO add your handling code here:
        String search = search_txt.getText();
        
        
        String filter =search_filter.getSelectedItem().toString();
        
        try{
            if(filter=="By Acc No."){
                    
                  customer_search obj = new  customer_search();
                  obj.AccNo_filter(customer_table, search);
                    
            }
            else if(filter=="By Name"){
                    customer_search obj = new  customer_search();
                    obj.name_filter(customer_table, search);
            }
        }catch(Exception e){
        System.out.println(e);

        }

        
    }//GEN-LAST:event_customer_search_butActionPerformed

    private void clear_search_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_search_txtActionPerformed
        // TODO add your handling code here:
        search_txt.setText("");
    }//GEN-LAST:event_clear_search_txtActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthActionPerformed

    private void bal_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bal_searchActionPerformed
        // TODO add your handling code here:
        
         account_operations obj = new account_operations();
         obj.view_balance(Integer.parseInt(acc_txt.getText()), name_field, acc_field, nic_field, balance_field);
    }//GEN-LAST:event_bal_searchActionPerformed

    private void officer_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officer_searchActionPerformed
        // TODO add your handling code here:
        
        manager_search obj = new manager_search();
        obj.manager_list(officer_list);
        
    }//GEN-LAST:event_officer_searchActionPerformed

    private void officer_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officer_addActionPerformed
        // TODO add your handling code here:
        int x = 0;
        String day_txt = day_off.getSelectedItem().toString();
       String month_txt =month_off.getSelectedItem().toString();
       String year_txt =year_off.getSelectedItem().toString();
       String dob_fixed =day_txt+"/"+month_txt+"/"+year_txt;
       String gender = null ;
       
       if(male_off.isSelected()){
           gender ="male";
       }else if(female_off.isSelected()){
           gender ="female";
       }
       dob_off.setText(dob_fixed);
       
       if(role_off.getSelectedItem().toString() == "Manager"){
        account_operations obj = new account_operations();
        x=obj.new_admin(name_off.getText().toString(), password_off.getText().toString(), dob_fixed, gender, address_off.getText().toString(), nic_off.getText().toString(), mobile_off.getText().toString(), role_off.getSelectedItem().toString());
       }else if(role_off.getSelectedItem().toString() == "Cashier"){
           account_operations obj = new account_operations();
        x=obj.new_cashier(name_off.getText().toString(), password_off.getText().toString(), dob_fixed, gender, address_off.getText().toString(), nic_off.getText().toString(), mobile_off.getText().toString(), role_off.getSelectedItem().toString());
      
       }
       if(x==1){
           JOptionPane.showMessageDialog(null, "'"+name_off.getText().toString()+"' added to system succesfully as a '"+role_off.getSelectedItem().toString()+"'");
       }else{
           JOptionPane.showMessageDialog(null, "Something went wrong!!! check and retry");
       }
       
    }//GEN-LAST:event_officer_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acc_creat_clear_but;
    private javax.swing.JButton acc_create_but;
    private javax.swing.JTextField acc_field;
    private javax.swing.JTextField acc_txt;
    private javax.swing.JComboBox<String> acc_type_combo;
    private javax.swing.JPanel account_panel;
    private javax.swing.JButton add_account_butt;
    private javax.swing.JPanel add_account_panel;
    private javax.swing.JButton add_officer_but;
    private javax.swing.JPanel add_officer_panel;
    private javax.swing.JTextField address_off;
    private javax.swing.JTextField address_txt;
    private javax.swing.JTextField after_withdraw;
    private javax.swing.JTextField amount_txt;
    private javax.swing.JButton bal_search;
    private javax.swing.JTextField bal_update;
    private javax.swing.JTextField balance_field;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton check_diposit;
    private javax.swing.JButton check_withdraw;
    private javax.swing.JButton clear_search_txt;
    private javax.swing.JTextField cus_name_txt;
    private javax.swing.JButton customer_list_but;
    private javax.swing.JPanel customer_list_panel;
    private javax.swing.JButton customer_search_but;
    private javax.swing.JTable customer_table;
    private javax.swing.JTextField date;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JComboBox<String> day_off;
    private javax.swing.JTextField diposit_amount;
    private javax.swing.JButton diposit_but;
    private javax.swing.JTextField dob_off;
    private javax.swing.JTextField dob_txt;
    private javax.swing.JRadioButton female_off;
    private javax.swing.JRadioButton female_radio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton logout_but;
    private javax.swing.JRadioButton male_off;
    private javax.swing.JRadioButton male_radio;
    private javax.swing.JTextField mobile_off;
    private javax.swing.JTextField mobile_txt;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JComboBox<String> month_off;
    private javax.swing.JTextField name_field;
    private javax.swing.JTextField name_off;
    private javax.swing.JTextField nic_field;
    private javax.swing.JTextField nic_off;
    private javax.swing.JTextField nic_txt;
    private javax.swing.JButton off_cleat;
    private javax.swing.JButton officer_add;
    private javax.swing.JTable officer_list;
    private javax.swing.JPanel officer_list_pane;
    private javax.swing.JButton officer_list_panel;
    private javax.swing.JPanel officer_panel;
    private javax.swing.JButton officer_search;
    private javax.swing.JTextField password_off;
    private javax.swing.JComboBox<String> role_off;
    private javax.swing.JButton search_all;
    private javax.swing.JComboBox<String> search_filter;
    private javax.swing.JTextField search_txt;
    private javax.swing.JLayeredPane sub_panel;
    private javax.swing.JTextField t_accNo;
    private javax.swing.JTextField t_bal;
    private javax.swing.JTextField t_name;
    private javax.swing.JPanel transaction_panel;
    private javax.swing.JButton transaction_search;
    private javax.swing.JButton view_bal_but;
    private javax.swing.JPanel view_bal_panel;
    private javax.swing.JTextField withdraw_amount;
    private javax.swing.JButton withdraw_but;
    private javax.swing.JComboBox<String> year;
    private javax.swing.JComboBox<String> year_off;
    // End of variables declaration//GEN-END:variables
}
